# 1. Write a python program to read the employee details as input from the user including employee name, employee number, designation, salary, department name, department number, manager name and print all the details using print statement.
name = input("Enter Employee Name: ")
number = input("Enter Employee Number: ")
designation = input("Enter Designation: ")
salary = int(input("Enter Salary: "))
dept_name = input("Enter Department Name: ")
dept_number = input("Enter Department Number: ")
manager_name = input("Enter Manager Name: ")
print("\n--- Employee Details ---")
print("Name: ",name)
print("Employee Number: ",number)
print("Designation: ",designation)
print("Salary: ₹",salary)
print("Department Name: ",dept_name)
print("Department Number: ",dept_number)
print("Manager Name: ",manager_name)